SRC_DIR := src
OBJ_DIR := obj
OUT_DIR := output
TEST_DIR := test
DOC_DIR := doc
CHK_DIR := $(TEST_DIR)/check
PROF_DIR := $(TEST_DIR)/profile
COV_DIR := $(TEST_DIR)/coverage
H_DIR := include
TARGET := ./kenken



## make [all]    Build all

all: package $(DOC_DIR) $(OBJ_DIR) $(OUT_DIR)
	@(cd $(SRC_DIR) && $(MAKE) $@)

$(OBJ_DIR):
	mkdir $@

$(OUT_DIR):
	mkdir $@

## make package  Manage dependancies

package:
	@(printf "%b\n" "If the libz3-dev package is not installed on your device,\
 you can't compile the Kenken project.\nYou can download it here:\
 https://github.com/Z3Prover/z3")



## make check    Run coverage tests

check: $(COV_DIR)
	@(cd $(SRC_DIR) && $(MAKE) -i $@)

cover_tests:
	@(sh $(CHK_DIR)/coverage_tests.sh)

$(COV_DIR):
	mkdir $@


## make profile  Run performance and load tests

profile:
	@(sh $(PROF_DIR)/profile.sh)


## make clean    Remove all files generated by make

clean: 
	@(cd $(SRC_DIR) && $(MAKE) $@)



## make help     Display this help

help:
	@fgrep -h "## " $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/## //'
